Add step to get publishable_api_key for frontend

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,34 +1,34 @@
-FROM node:23.7-bookworm-slim AS base
-
-FROM base AS dependency-installer
-WORKDIR /opt/medusa/deps
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
-RUN \
-  if [ -f yarn.lock ]; then corepack enable yarn && yarn --immutable; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+ARG NODE_VERSION=23.7
+FROM node:${NODE_VERSION}-bookworm-slim AS base
 
 FROM base AS builder
 WORKDIR /opt/medusa/build
-COPY --from=dependency-installer /opt/medusa/deps/node_modules ./node_modules
+COPY package*.json yarn.lock* pnpm-lock.yaml* ./
+# Install dependencies
+RUN \
+  if [ -f yarn.lock ]; then corepack enable yarn && yarn install; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Build the application
 COPY . .
 RUN \
-  if [ -f yarn.lock ]; then corepack enable && yarn run build; \
+  if [ -f yarn.lock ]; then yarn run build; \
   elif [ -f package-lock.json ]; then npm run build; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-  else echo "Lockfile not found." && exit 1; \
+  elif [ -f pnpm-lock.yaml ]; then pnpm run build; \
   fi
 
 FROM base AS runner
 RUN apt-get update \
   && apt-get install --no-install-recommends -y tini=0.19.0-1 \
-  && rm -rf /var/lib/apt/lists/*
+  && apt-get clean \
+  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 USER node
 WORKDIR /opt/medusa
-COPY --from=dependency-installer --chown=node:node /opt/medusa/deps/node_modules ./.medusa/server/node_modules
 COPY --from=builder --chown=node:node /opt/medusa/build .
+COPY --from=builder --chown=node:node /opt/medusa/build/node_modules ./.medusa/server/node_modules
 ARG PORT=9000
 ARG NODE_ENV=production
 ENV PORT=$PORT
diff --git a/storefront/Dockerfile b/storefront/Dockerfile
--- a/storefront/Dockerfile
+++ b/storefront/Dockerfile
@@ -1,27 +1,36 @@
-FROM node:23.7-bookworm-slim AS base
+ARG NODE_VERSION=23.7
+FROM node:${NODE_VERSION}-bookworm-slim AS base
 
 FROM base AS builder
 WORKDIR /opt/storefront/build
-RUN env
 ARG MEDUSA_BACKEND_URL=http://host.docker.internal:9000
 ARG NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=pk_test_123
 ENV MEDUSA_BACKEND_URL=${MEDUSA_BACKEND_URL}
 ENV NEXT_PUBLIC_MEDUSA_BACKEND_URL=${MEDUSA_BACKEND_URL}
 ENV NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=$NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
+
+COPY package*.json yarn.lock* pnpm-lock.yaml* ./
+# Install dependencies
+RUN \
+  if [ -f yarn.lock ]; then corepack enable yarn && yarn install; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Build the application
 COPY . .
 RUN \
-  if [ -f yarn.lock ]; then corepack enable yarn \
-    && yarn install \
-    && yarn run build; \
+  if [ -f yarn.lock ]; then yarn run build; \
   elif [ -f package-lock.json ]; then npm run build; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-  else echo "Lockfile not found." && exit 1; \
+  elif [ -f pnpm-lock.yaml ]; then pnpm run build; \
   fi
 
 FROM base AS runner
 RUN apt-get update \
   && apt-get install --no-install-recommends -y tini=0.19.0-1 \
-  && rm -rf /var/lib/apt/lists/*
+  && apt-get clean \
+  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 USER node
 WORKDIR /opt/storefront
 COPY --from=builder --chown=node:node /opt/storefront/build/ .
